### ISSUE TITLE
Wikipedia Page Source has changed

### ISSUE THREAD

**Issue by codified45** [learn-co-curriculum/phase-0-the-dom-dev-tools#5]
### Canvas Link

https://learning.flatironschool.com/courses/6190/pages/changing-the-dom-with-devtools-and-javascript?module_item_id=526876#:~:text=Next%2C%20locate%20the%20h1%20element%20nested%20inside%20the%20%22content%22%20div.%20It%20should%20look%20something%20like%20this%3A

### Concern

The h1 we are looking for in the example (to delete the "Ada Lovelace" header) is now nested 6 levels deep in the source of Wikipedia's page, requiring clicking through more disclosure triangles, so perhaps the photo provided as a guide should be updated for ease of following along.  

<img width="803" alt="Screen Shot 2023-02-04 at 5 43 28 PM" src="https://user-images.githubusercontent.com/45667207/216793684-5b778e82-cb21-4f0f-8a78-4a981e23a170.png">

**Comment by lizbur10** [comment]
Thanks @codified45! The screenshots and instructions have been updated to reflect the changes. 💙
